apiVersion: v1
kind: Service
metadata:
  name: glenn-loadbalancer-service
  namespace: glenn-eks-activity
spec:
  type: LoadBalancer
  selector:
    app: httpd-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678